### PR TITLE
Welcome to 2017

### PR DESCRIPTION
**Pull request by animaux**
+ PHP7 support
+ included [PR](https://github.com/6ui11em/uniqueindex/pull/2/commits/29c57a8b9d7b17fb67
ebf40d2547940f051d9262) 
+ support for association fields
+ TODO: fix possible mySQL issues with multilingual field
+ TODO: fix implode() error when deselecting all fields

### CODE REVIEW

**Comment by 6ui11em** [comment]
Thank you for the update. If you want I can transfer this repo, I'm not working with symphony anymore and I'm not maintaining it.

**Comment by animaux** [comment]
Gracias! I’d be happy to take it over, it really made my day today :)

**Comment by animaux** [comment]
I’d still love to take over this repo if you like. Other Symphony extensions as well, if you want.

**Comment by 6ui11em** [comment]
Hi, I tried to transfer the repo but it says animaux/uniqueindex already exist.

**Comment by animaux** [comment]
Ah, I see. I’ve deleted my fork. Would you please try again?

**Comment by 6ui11em** [comment]
Ok, just transferred. Thank you for taking care of it.

**Comment by animaux** [comment]
Great! Many thanks for creating it and letting it go `:)`

**Comment by animaux** [comment]
Could you also remove it from the extensions-site, please? http://symphonyextensions.com/extensions/uniqueindex/ Just login via github (top-left) and use the »Remove extension from site« link.

**Comment by 6ui11em** [comment]
Ok, just removed.

**Comment by animaux** [comment]
Brilliant, thanks!

**Pull request merged**
